apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: alpinetech/exchange
      context: ../exchange
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
