# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['configprops', 'env', 'health', 'info', 'jhimetrics', 'logfile', 'loggers', 'prometheus', 'threaddump']
  endpoint:
    health:
      show-details: when_authorized
      roles: 'ROLE_ADMIN'
    jhimetrics:
      enabled: true
  info:
    git:
      mode: full
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true
  metrics:
    export:
      # Prometheus is the default metrics backend
      prometheus:
        enabled: true
        step: 60
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}
    web:
      server:
        request:
          autotime:
            enabled: true

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchAutoConfiguration,org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
  application:
    name: exchange
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: #spring.profiles.active#
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true
  mvc:
    favicon:
      enabled: false
  task:
    execution:
      thread-name-prefix: exchange-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: exchange-scheduling-
      pool:
        size: 2
  thymeleaf:
    mode: HTML
  output:
    ansi:
      console-available: true
  jms:
    pub-sub-domain: true
  activemq:
    packages:
      trust-all: true

server:
  servlet:
    session:
      cookie:
        http-only: true

# Properties to be exposed on the /info management endpoint
info:
  # Comma separated list of profiles that will trigger the ribbon to show
  display-ribbon-on-profiles: 'dev'

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  clientApp:
    name: 'exchangeApp'
  # By default CORS is disabled. Uncomment to enable.
  # cors:
  #     allowed-origins: "*"
  #     allowed-methods: "*"
  #     allowed-headers: "*"
  #     exposed-headers: "Authorization,Link,X-Total-Count"
  #     allow-credentials: true
  #     max-age: 1800
  mail:
    from: exchange@localhost
  swagger:
    default-include-pattern: /api/.*
    title: exchange API
    description: exchange API documentation
    version: 0.0.1
    terms-of-service-url:
    contact-name:
    contact-url:
    contact-email:
    license:
    license-url:
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:

avaloq-sandbox-host: https://api-qwgzy.emea.sandbox.avaloq.com
avaloq-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJhdWQiOiJzYW5kYm94Iiwic3ViIjoieHNlY2F6Iiwiand0IjoiZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKU1V6VXhNaUo5LmV5SmhkV1FpT2lKQlZrRk1UMUVpTENKemRXSWlPaUpEU1UwaUxDSmhkbkZmY205c1pYTWlPbHNpY205c1pWOWhkM05mZFhObGNpSmRMQ0pwYzNNaU9pSktWMVJRY205MmFXUmxjaUlzSW1WNGNDSTZNVFU1TlRZNE5qZzNNeXdpYVdGMElqb3hOVGsxTmpjeU5EY3pMQ0poZG1Gc2IzRmZZblZmYVdRaU9pSTVJaXdpYW5ScElqb2lVV05OYVVJNGVqZEZPVmh4VW5ob1FUQlFXVWQwZHlJc0ltRjJjVjlpZFNJNklrRkJRU0o5LnEwWExLWTJxek43d0hsRm1tZWk4R3NnVm9JX19fREVpMnVWNFRJVmt0MGV1cFRUUjFPR1pjUFZpUDBmTW5qaW5IVFo3aVhtQm51b3k2NU81UkM2Y0JtcWFSdGI0VXBDOVpfR1JWM1QydThpSlAtSDNhcEQxRUZPVjdjbmgzVEgycE9tVFBaYm5ISUQ5MDFUYnVaZXRmQnBsOTlweDRQZTY5WFB3ajZEQ1hieFV0VkRsTk91REJaWmpBcm5EU3NSS2d4S3ZWMk1idnQzSHNoSnpQaEdRNnYwQlVFeU5nb2xTR2VqZFZXMi1uMnNNa09VcjhJLWJ5ZlI3YXdBSzMyRjhES19tTFQ3T1NPQWhhcjQ4TkE2SlRRT3R5NkVSQThiNjl5czVQcmFXZ19IRnFOZnJsUXo3N2oxMkNiNkxzdV94eFVwUFpKbThTVzByV1JWMXZ0UlR3dyIsImlzcyI6IkpXVFByb3ZpZGVyIiwic2ItaWQiOiJxd2d6eSIsImV4cCI6MTU5NTY4Njg3MywiaWF0IjoxNTk1NjcyNDczLCJqdGkiOiJfY2pCRm5zVHB4MDNSVFhvVTJHdGZnIn0.kKmJekg0oOBrq3jiHKUHwRTvbu3M3r0YaD6C_-2txdMpHQTsavEjCk4DQGb7t34-CgAv7RLkuUIO97df_QlfWU52GjyMDJm_EzwNmE1xWiK3oxFoAPFTUKm15grvPtSHoI9pSGEctsjBVJMps9oOKVLqpYZe-Duted01iJf7-NKPBbGrcSTXV5pRbOYZ_3n5tLjp802tBOvlty7m6DPabij45dRYXvKf7WsQJ4oNAucD7qqE8PSYhK7nuCKFT2z9ETpebuaFgXeviIIk6ys15Gk4bGcpUCTNRKUQvKhPmw2n_O3h_ahUeLfhvxG-teeGxsm4wcFKACP9wW2E1w6DZg
