# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    io.github.jhipster: DEBUG
    swiss.alpinetech.exchange: DEBUG

management:
  health:
    elasticsearch:
      enabled: false

spring:
  profiles:
    active: dev
    include:
      - swagger
      # Uncomment to activate TLS for the dev profile
      #- tls
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/exchange;DB_CLOSE_DELAY=-1
    username: exchange
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  data:
    elasticsearch:
      rest:
        uris: http://localhost:9200
      properties:
        path:
          home: target/elasticsearch
        http:
          enabled: true
          port: 9200
          cors.allow-origin: http://localhost:1358
          cors.enabled: false
          cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
          cors.allow-credentials: false
        cluster.routing.allocation.disk.threshold_enabled: false
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev, faker
  mail:
    host: localhost
    port: 8025
    username:
    password:
    protocol: smtp

  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50

  jms:
    pub-sub-domain: true

server:
  port: 8080

# ===================================================================
# Exchange specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  cache: # Cache configuration
    ehcache: # Ehcache configuration
      time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
      max-entries: 100 # Number of objects in each cache entry
  # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: OTE5MDRlYjNkYWY3ZGE3NmMwNTNiMmY5MTM0NTViODc1ZTAxN2JhOWY1NTM1NzJlOGRhYzZiMTY3ZDJmZTg2NDE1NTkxOGMxZWJiMTU1NmU1Y2QwY2I3YTQ0OGJkOTZlNDY0NWM1MWI2OWQ3NDViZjNkZmJmMjA2MmNmMTAyYWY=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail: # specific JHipster mail property, for standard properties see MailProperties
    base-url: http://127.0.0.1:8080
  metrics:
    logs: # Reports metrics in the logs
      enabled: false
      report-frequency: 60 # in seconds
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
  audit-events:
    retention-period: 30 # Number of days before audit events are deleted.

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:

avaloq-sandbox-host: https://api-qwgzy.emea.sandbox.avaloq.com
avaloq-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJhdWQiOiJzYW5kYm94Iiwic3ViIjoieHNlY2F6Iiwiand0IjoiZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKU1V6VXhNaUo5LmV5SmhkV1FpT2lKQlZrRk1UMUVpTENKemRXSWlPaUpEU1UwaUxDSmhkbkZmY205c1pYTWlPbHNpY205c1pWOWhkM05mZFhObGNpSmRMQ0pwYzNNaU9pSktWMVJRY205MmFXUmxjaUlzSW1WNGNDSTZNVFU1TlRZNE5qZzNNeXdpYVdGMElqb3hOVGsxTmpjeU5EY3pMQ0poZG1Gc2IzRmZZblZmYVdRaU9pSTVJaXdpYW5ScElqb2lVV05OYVVJNGVqZEZPVmh4VW5ob1FUQlFXVWQwZHlJc0ltRjJjVjlpZFNJNklrRkJRU0o5LnEwWExLWTJxek43d0hsRm1tZWk4R3NnVm9JX19fREVpMnVWNFRJVmt0MGV1cFRUUjFPR1pjUFZpUDBmTW5qaW5IVFo3aVhtQm51b3k2NU81UkM2Y0JtcWFSdGI0VXBDOVpfR1JWM1QydThpSlAtSDNhcEQxRUZPVjdjbmgzVEgycE9tVFBaYm5ISUQ5MDFUYnVaZXRmQnBsOTlweDRQZTY5WFB3ajZEQ1hieFV0VkRsTk91REJaWmpBcm5EU3NSS2d4S3ZWMk1idnQzSHNoSnpQaEdRNnYwQlVFeU5nb2xTR2VqZFZXMi1uMnNNa09VcjhJLWJ5ZlI3YXdBSzMyRjhES19tTFQ3T1NPQWhhcjQ4TkE2SlRRT3R5NkVSQThiNjl5czVQcmFXZ19IRnFOZnJsUXo3N2oxMkNiNkxzdV94eFVwUFpKbThTVzByV1JWMXZ0UlR3dyIsImlzcyI6IkpXVFByb3ZpZGVyIiwic2ItaWQiOiJxd2d6eSIsImV4cCI6MTU5NTY4Njg3MywiaWF0IjoxNTk1NjcyNDczLCJqdGkiOiJfY2pCRm5zVHB4MDNSVFhvVTJHdGZnIn0.kKmJekg0oOBrq3jiHKUHwRTvbu3M3r0YaD6C_-2txdMpHQTsavEjCk4DQGb7t34-CgAv7RLkuUIO97df_QlfWU52GjyMDJm_EzwNmE1xWiK3oxFoAPFTUKm15grvPtSHoI9pSGEctsjBVJMps9oOKVLqpYZe-Duted01iJf7-NKPBbGrcSTXV5pRbOYZ_3n5tLjp802tBOvlty7m6DPabij45dRYXvKf7WsQJ4oNAucD7qqE8PSYhK7nuCKFT2z9ETpebuaFgXeviIIk6ys15Gk4bGcpUCTNRKUQvKhPmw2n_O3h_ahUeLfhvxG-teeGxsm4wcFKACP9wW2E1w6DZg
