apiVersion: v1
kind: Service
metadata:
  name: exchange
  namespace: default
  labels:
    app: exchange
spec:
  selector:
    app: exchange
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
