version: '2.1'
services:
  exchange-activemq:
    image: rmohr/activemq:5.15.9
    ports:
      # mqtt
      - '1883:1883'
      # amqp
      - '5672:5672'
      # ui
      - '8161:8161'
      # stomp
      - '61613:61613'
      # ws
      - '61614:61614'
      # jms
      - '61616:61616'
    volumes:
      - ./activemq/conf:/opt/activemq/conf/
      - ./volumes/activemq-data/data:/opt/activemq/data/
