version: '2'
services:
  exchange-app:
    image: alpinetech/exchange
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://exchange-mysql:3306/exchange?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://exchange-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://exchange-elasticsearch:9200
    ports:
      - 8080:8080
  exchange-mysql:
    extends:
      file: mysql.yml
      service: exchange-mysql
  exchange-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: exchange-elasticsearch
  exchange-activemq:
    extends:
      file: activemq.yml
      service: exchange-activemq
