export const enum COUNTRY {
  FRANCE = 'FRANCE',
  USA = 'USA',
  SWITZERLAND = 'SWITZERLAND',
  GERMANY = 'GERMANY',
  ITALY = 'ITALY',
  IRAN = 'IRAN',
  CHINA = 'CHINA',
  NORTH_KOREA = 'NORTH_KOREA',
  CANADA = 'CANADA',
  SENEGAL = 'SENEGAL'
}
